// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnj1O8ReRzpE4hOyCTIEVFkilYb07QwIM',
    appId: '1:760726058558:web:ec2ce3840a1e799754436f',
    messagingSenderId: '760726058558',
    projectId: 'accesibilidad-flutterflow',
    authDomain: 'accesibilidad-flutterflow.firebaseapp.com',
    storageBucket: 'accesibilidad-flutterflow.firebasestorage.app',
    measurementId: 'G-DEWYZRHX8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgI_lTgQk9gBFp0ysON07I08RMYNu0a20',
    appId: '1:760726058558:android:214db455a7dd133e54436f',
    messagingSenderId: '760726058558',
    projectId: 'accesibilidad-flutterflow',
    storageBucket: 'accesibilidad-flutterflow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJHxiXPLmZ9vyjct_Lrixff-dTQ0_fcaY',
    appId: '1:760726058558:ios:bd15de37a2367ffa54436f',
    messagingSenderId: '760726058558',
    projectId: 'accesibilidad-flutterflow',
    storageBucket: 'accesibilidad-flutterflow.firebasestorage.app',
    iosBundleId: 'com.mycompany.practica2adpt',
  );

}